apiVersion: v1
kind: Secret
metadata:
  name: ha-example-test-tls
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    
  # This is an example, remember to not use in production
  tls.key: |
    
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-example-preshared-auth-secret
type: Opaque
data:
  # This is an example, remember to not use in production
  preshared_auth_key: Z2ZwWHRyM0VaeUdMbTBOdndDY2F1WmtRZEg1RXQ4QWFZQXdSVW8x
---
apiVersion: pubsubplus.solace.com/v1beta1
kind: PubSubPlusEventBroker
metadata:
  name: ha-example-presahred-auth
spec:
  redundancy: false
  timezone: UTC
  extraEnvVars:
    - name: HA
      value: "CustomPreSharedAuth"
  podDisruptionBudgetForHA: true
  preSharedAuthKeySecret: ha-example-preshared-auth-secret
  podLabels:
    "DeploymentType": "HA"
    "DeploymentTestMode": "CustomPreSharedAuth"
  podAnnotations:
    "DeploymentType": "HA"
    "DeploymentTestMode": "CustomPreSharedAuth"
  updateStrategy: manualPodRestart
  securityContext: {}
  tls:
    enabled: true
    serverTlsConfigSecret: ha-example-test-tls
  service:
    type: LoadBalancer
    ports:
      - servicePort: 2222
        containerPort: 2222
        protocol: TCP
        name: tcp-ssh
      - servicePort: 8080
        containerPort: 8080
        protocol: TCP
        name: tcp-semp
      - servicePort: 1943
        containerPort: 1943
        protocol: TCP
        name: tls-semp
      - servicePort: 55555
        containerPort: 55555
        protocol: TCP
        name: tcp-smf
      - servicePort: 55003
        containerPort: 55003
        protocol: TCP
        name: tcp-smfcomp
      - servicePort: 55443
        containerPort: 55443
        protocol: TCP
        name: tls-smf
      - servicePort: 55556
        containerPort: 55556
        protocol: TCP
        name: tcp-smfroute
      - servicePort: 8008
        containerPort: 8008
        protocol: TCP
        name: tcp-web
      - servicePort: 1443
        containerPort: 1443
        protocol: TCP
        name: tls-web
      - servicePort: 9000
        containerPort: 9000
        protocol: TCP
        name: tcp-rest
      - servicePort: 9443
        containerPort: 9443
        protocol: TCP
        name: tls-rest
      - servicePort: 5672
        containerPort: 5672
        protocol: TCP
        name: tcp-amqp
      - servicePort: 5671
        containerPort: 5671
        protocol: TCP
        name: tls-amqp
      - servicePort: 1883
        containerPort: 1883
        protocol: TCP
        name: tcp-mqtt
      - servicePort: 8883
        containerPort: 8883
        protocol: TCP
        name: tls-mqtt
      - servicePort: 8000
        containerPort: 8000
        protocol: TCP
        name: tcp-mqttweb
      - servicePort: 8443
        containerPort: 8443
        protocol: TCP
        name: tls-mqttweb
  monitoring:
    enabled: true
    image:
      repository: ghcr.io/solacedev/pubsubplus-prometheus-exporter
      pullPolicy: Always